/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of filterable layers for a WebMap */
        get: {
            parameters: {
                query?: {
                    /** @description Language for filter labels and descriptions */
                    lang?: "en" | "it" | "de" | "fr";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of filterable layers */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "webmapId": "SwissTopoMap",
                         *       "layers": [
                         *         {
                         *           "id": "tecto_units_augm",
                         *           "name": "Tectonic Units",
                         *           "filterable": true,
                         *           "availableFilters": [
                         *             {
                         *               "id": "f-chronostrat-term",
                         *               "name": "Filter by Chronostratigraphy term",
                         *               "title": "Filter by Chronostratigraphy term",
                         *               "description": "Filter by chronostratigraphic intervals"
                         *             },
                         *             {
                         *               "id": "f-tectonic-term",
                         *               "name": "Filter by Tectonic Units term",
                         *               "title": "Filter by Tectonic Units term",
                         *               "description": "Filter by tectonic units"
                         *             },
                         *             {
                         *               "id": "f-byAttribute",
                         *               "name": "Filter by Attribute",
                         *               "title": "Filter by Attribute",
                         *               "description": "Filter by attribute key/value"
                         *             }
                         *           ]
                         *         },
                         *         {
                         *           "id": "gc_bedrock",
                         *           "name": "GC_BEDROCK",
                         *           "filterable": true,
                         *           "availableFilters": [
                         *             {
                         *               "id": "f-chronostrat-term",
                         *               "name": "Filter by Chronostratigraphy term",
                         *               "title": "Filter by Chronostratigraphy term",
                         *               "description": "Filter by chronostratigraphic intervals"
                         *             },
                         *             {
                         *               "id": "f-tectonic-term",
                         *               "name": "Filter by Tectonic Units term",
                         *               "title": "Filter by Tectonic Units term",
                         *               "description": "Filter by tectonic units"
                         *             },
                         *             {
                         *               "id": "f-lithostrat-term",
                         *               "name": "Filter by Lithostratigraphy term",
                         *               "title": "Filter by Lithostratigraphy term",
                         *               "description": "Filter by lithostratigraphic units"
                         *             },
                         *             {
                         *               "id": "f-lithology-term",
                         *               "name": "Filter by Lithology term",
                         *               "title": "Filter by Lithology term",
                         *               "description": "Filter by lithology classes"
                         *             },
                         *             {
                         *               "id": "f-byAttribute",
                         *               "name": "Filter by Attribute",
                         *               "title": "Filter by Attribute",
                         *               "description": "Filter by attribute key/value"
                         *             }
                         *           ]
                         *         },
                         *         {
                         *           "id": "gc_unco_deposits",
                         *           "name": "GC_UNCO_DEPOSITS",
                         *           "filterable": true,
                         *           "availableFilters": [
                         *             {
                         *               "id": "f-chronostrat-term",
                         *               "name": "Filter by Chronostratigraphy term",
                         *               "title": "Filter by Chronostratigraphy term",
                         *               "description": "Filter by chronostratigraphic intervals"
                         *             },
                         *             {
                         *               "id": "f-byAttribute",
                         *               "name": "Filter by Attribute",
                         *               "title": "Filter by Attribute",
                         *               "description": "Filter by attribute key/value"
                         *             }
                         *           ]
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["inline_response_200"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layers/{layerId}/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get enabled filters for a specific layer */
        get: {
            parameters: {
                query?: {
                    /** @description Language for filter labels and descriptions */
                    lang?: "en" | "it" | "de" | "fr";
                };
                header?: never;
                path: {
                    layerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Enabled filters for the specified layer */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["inline_response_200_1"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layers/{layerId}/defaultFilters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get default filters for a layer and a vocabulary term
         * @description Returns the default filters that should be applied to visualize the provided vocabulary term on the selected layer. The vocabulary is inferred from the term URI. If the layer does not support the inferred vocabulary, the endpoint returns an error.
         */
        get: {
            parameters: {
                query: {
                    /** @description Vocabulary term URI used to infer the vocabulary and build the default filter */
                    term: string;
                };
                header?: never;
                path: {
                    layerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default filters for the specified layer and term */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DefaultFiltersResponse"];
                    };
                };
                /** @description The layer does not support the vocabulary inferred from the provided term URI */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "code": 400,
                         *       "message": "Layer does not support the vocabulary inferred from the provided term"
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layers/{layerId}/attributeList": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get available attributes for filter by attribute on a specific layer */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    layerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Attribute list for the specified layer */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["inline_response_200_2"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocabularies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the list of available vocabularies */
        get: {
            parameters: {
                query?: {
                    /** @description Language for vocabulary labels */
                    lang?: "en" | "it" | "de" | "fr";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of vocabularies */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "vocabularies": [
                         *         {
                         *           "id": "chronostratigraphy",
                         *           "name": "Chronostratigraphy"
                         *         },
                         *         {
                         *           "id": "tectonic-units",
                         *           "name": "Tectonic Units"
                         *         },
                         *         {
                         *           "id": "lithostratigraphy",
                         *           "name": "Lithostratigraphy"
                         *         },
                         *         {
                         *           "id": "lithology",
                         *           "name": "Lithology"
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["VocabulariesList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocabularies/chronostratigraphy/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all Chronostratigraphy terms */
        get: {
            parameters: {
                query?: {
                    /** @description Language for vocabulary related data */
                    lang?: "en" | "it" | "de" | "fr";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of Chronostratigraphy terms */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "terms": [
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Chronostratigraphy/Phanerozoic",
                         *           "label": "Phanerozoic",
                         *           "description": "Mock description for the Phanerozoic chronostratigraphy term.",
                         *           "breadcrumbs": {
                         *             "0": "Chronostratigraphy",
                         *             "1": "Phanerozoic"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Chronostratigraphy/Paleozoic",
                         *           "label": "Paleozoic",
                         *           "description": "Mock description for the Paleozoic chronostratigraphy term.",
                         *           "breadcrumbs": {
                         *             "0": "Chronostratigraphy",
                         *             "1": "Paleozoic"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Chronostratigraphy/Cenozoic",
                         *           "label": "Cenozoic",
                         *           "description": "Mock description for the Cenozoic chronostratigraphy term.",
                         *           "breadcrumbs": {
                         *             "0": "Chronostratigraphy",
                         *             "1": "Cenozoic"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Chronostratigraphy/Mesozoic",
                         *           "label": "Mesozoic",
                         *           "description": "Mock description for the Mesozoic chronostratigraphy term.",
                         *           "breadcrumbs": {
                         *             "0": "Chronostratigraphy",
                         *             "1": "Mesozoic"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Chronostratigraphy/Proterozoic",
                         *           "label": "Proterozoic",
                         *           "description": "Mock description for the Proterozoic chronostratigraphy term.",
                         *           "breadcrumbs": {
                         *             "0": "Chronostratigraphy",
                         *             "1": "Proterozoic"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Chronostratigraphy/Paleogene",
                         *           "label": "Paleogene",
                         *           "description": "Mock description for the Paleogene chronostratigraphy term.",
                         *           "breadcrumbs": {
                         *             "0": "Chronostratigraphy",
                         *             "1": "Paleogene"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Chronostratigraphy/Quaternary",
                         *           "label": "Quaternary",
                         *           "description": "Mock description for the Quaternary chronostratigraphy term.",
                         *           "breadcrumbs": {
                         *             "0": "Chronostratigraphy",
                         *             "1": "Quaternary"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Chronostratigraphy/Neogene",
                         *           "label": "Neogene",
                         *           "description": "Mock description for the Neogene chronostratigraphy term.",
                         *           "breadcrumbs": {
                         *             "0": "Chronostratigraphy",
                         *             "1": "Neogene"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Chronostratigraphy/Tertiary",
                         *           "label": "Tertiary",
                         *           "description": "Mock description for the Tertiary chronostratigraphy term.",
                         *           "breadcrumbs": {
                         *             "0": "Chronostratigraphy",
                         *             "1": "Tertiary"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Chronostratigraphy/Cretaceous",
                         *           "label": "Cretaceous",
                         *           "description": "Mock description for the Cretaceous chronostratigraphy term.",
                         *           "breadcrumbs": {
                         *             "0": "Chronostratigraphy",
                         *             "1": "Cretaceous"
                         *           }
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["VocabularyTerms"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocabularies/tectonic-units/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all Tectonic Units terms */
        get: {
            parameters: {
                query?: {
                    /** @description Language for vocabulary related data */
                    lang?: "en" | "it" | "de" | "fr";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of Tectonic Units terms */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "terms": [
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/TectonicUnits/AutochthonousNorthAlpineForeland",
                         *           "label": "AutochthonousNorthAlpineForeland",
                         *           "description": "Mock description for the AutochthonousNorthAlpineForeland tectonic units term.",
                         *           "breadcrumbs": {
                         *             "0": "Tectonic Units",
                         *             "1": "AutochthonousNorthAlpineForeland"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/TectonicUnits/BresseGraben",
                         *           "label": "BresseGraben",
                         *           "description": "Mock description for the BresseGraben tectonic units term.",
                         *           "breadcrumbs": {
                         *             "0": "Tectonic Units",
                         *             "1": "BresseGraben"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/TectonicUnits/UpperRhineGraben",
                         *           "label": "UpperRhineGraben",
                         *           "description": "Mock description for the UpperRhineGraben tectonic units term.",
                         *           "breadcrumbs": {
                         *             "0": "Tectonic Units",
                         *             "1": "UpperRhineGraben"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/TectonicUnits/SouthGermanPlatform",
                         *           "label": "SouthGermanPlatform",
                         *           "description": "Mock description for the SouthGermanPlatform tectonic units term.",
                         *           "breadcrumbs": {
                         *             "0": "Tectonic Units",
                         *             "1": "SouthGermanPlatform"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/TectonicUnits/TransitionZoneBetweenDetachedAndAutochthonousNorthAlpineForeland",
                         *           "label": "TransitionZoneBetweenDetachedAndAutochthonousNorthAlpineForeland",
                         *           "description": "Mock description for the TransitionZoneBetweenDetachedAndAutochthonousNorthAlpineForeland tectonic units term.",
                         *           "breadcrumbs": {
                         *             "0": "Tectonic Units",
                         *             "1": "TransitionZoneBetweenDetachedAndAutochthonousNorthAlpineForeland"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/TectonicUnits/DetachedNorthAlpineForeland",
                         *           "label": "DetachedNorthAlpineForeland",
                         *           "description": "Mock description for the DetachedNorthAlpineForeland tectonic units term.",
                         *           "breadcrumbs": {
                         *             "0": "Tectonic Units",
                         *             "1": "DetachedNorthAlpineForeland"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/TectonicUnits/ExternalFoldedJura",
                         *           "label": "ExternalFoldedJura",
                         *           "description": "Mock description for the ExternalFoldedJura tectonic units term.",
                         *           "breadcrumbs": {
                         *             "0": "Tectonic Units",
                         *             "1": "ExternalFoldedJura"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/TectonicUnits/SubalpineMolasse",
                         *           "label": "SubalpineMolasse",
                         *           "description": "Mock description for the SubalpineMolasse tectonic units term.",
                         *           "breadcrumbs": {
                         *             "0": "Tectonic Units",
                         *             "1": "SubalpineMolasse"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/TectonicUnits/InternalFoldedJuraAndForelandPlateau",
                         *           "label": "InternalFoldedJuraAndForelandPlateau",
                         *           "description": "Mock description for the InternalFoldedJuraAndForelandPlateau tectonic units term.",
                         *           "breadcrumbs": {
                         *             "0": "Tectonic Units",
                         *             "1": "InternalFoldedJuraAndForelandPlateau"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/TectonicUnits/HegauVolcanicSuite",
                         *           "label": "HegauVolcanicSuite",
                         *           "description": "Mock description for the HegauVolcanicSuite tectonic units term.",
                         *           "breadcrumbs": {
                         *             "0": "Tectonic Units",
                         *             "1": "HegauVolcanicSuite"
                         *           }
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["VocabularyTerms"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocabularies/lithostratigraphy/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all Lithostratigraphy terms */
        get: {
            parameters: {
                query?: {
                    /** @description Language for vocabulary related data */
                    lang?: "en" | "it" | "de" | "fr";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of Lithostratigraphy terms */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "terms": [
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Lithostratigraphy/Servino",
                         *           "label": "Servino",
                         *           "description": "Mock description for the Servino lithostratigraphy term.",
                         *           "breadcrumbs": {
                         *             "0": "Lithostratigraphy",
                         *             "1": "Servino"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Lithostratigraphy/Grenzposidonienschichten",
                         *           "label": "Grenzposidonienschichten",
                         *           "description": "Mock description for the Grenzposidonienschichten lithostratigraphy term.",
                         *           "breadcrumbs": {
                         *             "0": "Lithostratigraphy",
                         *             "1": "Grenzposidonienschichten"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Lithostratigraphy/Flysch2",
                         *           "label": "Flysch2",
                         *           "description": "Mock description for the Flysch2 lithostratigraphy term.",
                         *           "breadcrumbs": {
                         *             "0": "Lithostratigraphy",
                         *             "1": "Flysch2"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Lithostratigraphy/Flysch3",
                         *           "label": "Flysch3",
                         *           "description": "Mock description for the Flysch3 lithostratigraphy term.",
                         *           "breadcrumbs": {
                         *             "0": "Lithostratigraphy",
                         *             "1": "Flysch3"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Lithostratigraphy/Flysch4",
                         *           "label": "Flysch4",
                         *           "description": "Mock description for the Flysch4 lithostratigraphy term.",
                         *           "breadcrumbs": {
                         *             "0": "Lithostratigraphy",
                         *             "1": "Flysch4"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Lithostratigraphy/Flysch5",
                         *           "label": "Flysch5",
                         *           "description": "Mock description for the Flysch5 lithostratigraphy term.",
                         *           "breadcrumbs": {
                         *             "0": "Lithostratigraphy",
                         *             "1": "Flysch5"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Lithostratigraphy/Flysch2a",
                         *           "label": "Flysch2a",
                         *           "description": "Mock description for the Flysch2a lithostratigraphy term.",
                         *           "breadcrumbs": {
                         *             "0": "Lithostratigraphy",
                         *             "1": "Flysch2a"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Lithostratigraphy/Flysch2b",
                         *           "label": "Flysch2b",
                         *           "description": "Mock description for the Flysch2b lithostratigraphy term.",
                         *           "breadcrumbs": {
                         *             "0": "Lithostratigraphy",
                         *             "1": "Flysch2b"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Lithostratigraphy/Flysch3a",
                         *           "label": "Flysch3a",
                         *           "description": "Mock description for the Flysch3a lithostratigraphy term.",
                         *           "breadcrumbs": {
                         *             "0": "Lithostratigraphy",
                         *             "1": "Flysch3a"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Lithostratigraphy/Flysch3b",
                         *           "label": "Flysch3b",
                         *           "description": "Mock description for the Flysch3b lithostratigraphy term.",
                         *           "breadcrumbs": {
                         *             "0": "Lithostratigraphy",
                         *             "1": "Flysch3b"
                         *           }
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["VocabularyTerms"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocabularies/lithology/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all Lithology terms */
        get: {
            parameters: {
                query?: {
                    /** @description Language for vocabulary related data */
                    lang?: "en" | "it" | "de" | "fr";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of Lithology terms */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "terms": [
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Lithology/Amphibolite",
                         *           "label": "Amphibolite",
                         *           "description": "Mock description for the Amphibolite lithology term.",
                         *           "breadcrumbs": {
                         *             "0": "Lithology",
                         *             "1": "Amphibolite"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Lithology/RockMafic",
                         *           "label": "RockMafic",
                         *           "description": "Mock description for the RockMafic lithology term.",
                         *           "breadcrumbs": {
                         *             "0": "Lithology",
                         *             "1": "RockMafic"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Lithology/AmphiboliteBanded",
                         *           "label": "AmphiboliteBanded",
                         *           "description": "Mock description for the AmphiboliteBanded lithology term.",
                         *           "breadcrumbs": {
                         *             "0": "Lithology",
                         *             "1": "AmphiboliteBanded"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Lithology/AmphiboliteGarnet",
                         *           "label": "AmphiboliteGarnet",
                         *           "description": "Mock description for the AmphiboliteGarnet lithology term.",
                         *           "breadcrumbs": {
                         *             "0": "Lithology",
                         *             "1": "AmphiboliteGarnet"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Lithology/AmphiboliteHornblende",
                         *           "label": "AmphiboliteHornblende",
                         *           "description": "Mock description for the AmphiboliteHornblende lithology term.",
                         *           "breadcrumbs": {
                         *             "0": "Lithology",
                         *             "1": "AmphiboliteHornblende"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Lithology/AmphiboliteMigmatitic",
                         *           "label": "AmphiboliteMigmatitic",
                         *           "description": "Mock description for the AmphiboliteMigmatitic lithology term.",
                         *           "breadcrumbs": {
                         *             "0": "Lithology",
                         *             "1": "AmphiboliteMigmatitic"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Lithology/RockCrystalline",
                         *           "label": "RockCrystalline",
                         *           "description": "Mock description for the RockCrystalline lithology term.",
                         *           "breadcrumbs": {
                         *             "0": "Lithology",
                         *             "1": "RockCrystalline"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Lithology/Eclogite",
                         *           "label": "Eclogite",
                         *           "description": "Mock description for the Eclogite lithology term.",
                         *           "breadcrumbs": {
                         *             "0": "Lithology",
                         *             "1": "Eclogite"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Lithology/Serpentinite",
                         *           "label": "Serpentinite",
                         *           "description": "Mock description for the Serpentinite lithology term.",
                         *           "breadcrumbs": {
                         *             "0": "Lithology",
                         *             "1": "Serpentinite"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://dev-lexic.swissgeol.ch/Lithology/Prasinite",
                         *           "label": "Prasinite",
                         *           "description": "Mock description for the Prasinite lithology term.",
                         *           "breadcrumbs": {
                         *             "0": "Lithology",
                         *             "1": "Prasinite"
                         *           }
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["VocabularyTerms"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocabularies/chronostratigraphy/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get layers filterable by Chronostratigraphy vocabulary */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of layers with filters on Chronostratigraphy vocabulary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "layers": [
                         *         {
                         *           "id": "tecto_units_augm",
                         *           "name": "Tectonic Units"
                         *         },
                         *         {
                         *           "id": "gc_bedrock",
                         *           "name": "GC_BEDROCK"
                         *         },
                         *         {
                         *           "id": "gc_unco_deposits",
                         *           "name": "GC_UNCO_DEPOSITS"
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["VocabularyLayersResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocabularies/tectonic-units/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get layers filterable by Tectonic Units vocabulary */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of layers with filters on Tectonic Units vocabulary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "layers": [
                         *         {
                         *           "id": "tecto_units_augm",
                         *           "name": "Tectonic Units"
                         *         },
                         *         {
                         *           "id": "gc_bedrock",
                         *           "name": "GC_BEDROCK"
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["VocabularyLayersResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocabularies/lithostratigraphy/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get layers filterable by Lithostratigraphy vocabulary */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of layers with filters on Lithostratigraphy vocabulary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "layers": [
                         *         {
                         *           "id": "gc_bedrock",
                         *           "name": "GC_BEDROCK"
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["VocabularyLayersResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocabularies/lithology/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get layers filterable by Lithology vocabulary */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of layers with filters on Lithology vocabulary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "layers": [
                         *         {
                         *           "id": "gc_bedrock",
                         *           "name": "GC_BEDROCK"
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["VocabularyLayersResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generateWmsRequest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a WMS Base URL for a filtered layer (semantic query applied) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "webmapId": "SwissTopoMap",
                     *       "layerId": "tecto_units_augm",
                     *       "filters": [
                     *         {
                     *           "filterId": "f-tectonic-term",
                     *           "parameters": {
                     *             "term": "https://dev-lexic.swissgeol.ch/TectonicUnits/AutochthonousNorthAlpineForeland",
                     *             "includeNarrowers": true
                     *           }
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["WmsRequest"];
                };
            };
            responses: {
                /** @description WMS endpoint with filtered layer */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "url": "https://dev-webmap-api.swissgeol.ch/wms",
                         *       "body": "REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=swisstopo:filtered&TRANSPARENT=true&LAYERS=tecto_units_augm&TILED=true&SEMANTIC_FILTER=\"tecto_lexic\" IN ( get_terms( \"North Alpine Foreland\" , True ) )&CRS=EPSG:2056",
                         *       "mimeType": "image/png",
                         *       "note": "The WMS URL includes encoded semantic query parameters."
                         *     }
                         */
                        "application/json": components["schemas"]["WmsResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve WMS service information
         * @description This endpoint returns information about the WMS service or available maps depending on the specified parameters.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful WMS response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/png": string;
                    };
                };
                400: components["responses"]["BadRequest"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        /**
         * Retrieve WMS service information
         * @description This endpoint returns information about the WMS service or available maps depending on the specified parameters.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful WMS response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/png": string;
                    };
                };
                400: components["responses"]["BadRequest"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Layer: {
            id?: string;
            name?: string;
            filterable?: boolean;
            availableFilters?: components["schemas"]["Layer_availableFilters"][];
        };
        Filter: {
            /** @enum {string} */
            id?: "f-chronostrat-term" | "f-tectonic-term" | "f-lithostrat-term" | "f-lithology-term" | "f-byAttribute";
            name?: string;
            title?: string;
            description?: string;
        };
        ChronostratigraphyFilterParameter: {
            /** @enum {string} */
            type: "Younger" | "From-To" | "Older";
            /** @description From term (required if type is From-To or Older) */
            from?: string;
            /** @description To term (required if type is From-To or Younger) */
            to?: string;
        };
        TermFilterParameter: {
            /** @description Selected term from vocabulary */
            term: string;
            /**
             * @description Whether to include narrower terms
             * @default true
             */
            includeNarrowers: boolean;
        };
        ByAttributeFilterParameter: {
            /** @description Attribute key available from /layers/{layerId}/attributeList */
            attribute: string;
            /** @description Attribute value to match */
            value: string | number | boolean;
        };
        WmsRequest: {
            webmapId: string;
            layerId: string;
            /** @description List of applied filters and their parameter values */
            filters?: components["schemas"]["WmsRequest_filters"][];
        };
        WmsRequest_filters: {
            /** @enum {string} */
            filterId?: "f-chronostrat-term" | "f-tectonic-term" | "f-lithostrat-term" | "f-lithology-term" | "f-byAttribute";
            parameters?: components["schemas"]["ChronostratigraphyFilterParameter"] | components["schemas"]["TermFilterParameter"] | components["schemas"]["ByAttributeFilterParameter"];
        };
        WmsResponse: {
            /**
             * Format: uri
             * @description WMS endpoint URL to call.
             * @example https://dev-webmap-api.swissgeol.ch/wms
             */
            url: string;
            /**
             * @description WMS request parameter string generated by /generateWmsRequest.
             * @example REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image/png&STYLES=swisstopo:filtered&TRANSPARENT=true&LAYERS=tecto_units_augm&TILED=true&SEMANTIC_FILTER="tecto_lexic" IN ( get_terms( "North Alpine Foreland" , True ) )&CRS=EPSG:2056
             */
            body: string;
            /** @example image/png */
            mimeType: string;
            /** @example WMS URL includes encoded semantic query parameters. */
            note: string;
        };
        Error: {
            code?: number;
            message?: string;
        };
        inline_response_200: {
            webmapId?: string;
            layers?: components["schemas"]["Layer"][];
        };
        inline_response_200_1: {
            layerId?: string;
            filters?: components["schemas"]["Filter"][];
        };
        inline_response_200_2: {
            layerId?: string;
            attributes?: string[];
        };
        Layer_availableFilters: {
            id?: string;
            name?: string;
            title?: string;
            description?: string;
        };
        DefaultFiltersResponse: {
            layerId: string;
            /** @description Default filters to apply when visualizing the selected vocabulary term on the map */
            filters: components["schemas"]["WmsRequest_filters"][];
        };
        VocabulariesList: {
            vocabularies?: components["schemas"]["VocabularyDescriptor"][];
        };
        VocabularyDescriptor: {
            id?: string;
            name?: string;
        };
        VocabularyTerms: {
            terms?: components["schemas"]["VocabularyTerm"][];
        };
        VocabularyTerm: {
            /** Format: uri */
            term?: string;
            label?: string;
            description?: string;
            /** @description Ordered breadcrumb map. Keys represent numeric positions and are serialized as strings in JSON, for example "0", "1", "2". */
            breadcrumbs?: {
                [key: string]: string;
            };
        };
        VocabularyLayerRef: {
            id?: string;
            name?: string;
        };
        VocabularyLayersResponse: {
            layers?: components["schemas"]["VocabularyLayerRef"][];
        };
    };
    responses: {
        /** @description Bad Request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": 500,
                 *       "message": "Internal server error"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
