/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of filterable layers for a WebMap */
        get: {
            parameters: {
                query?: {
                    /** @description Language for filter labels and descriptions */
                    lang?: "en" | "it" | "de" | "fr";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of filterable layers */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "webmapId": "SwissTopoMap",
                         *       "layers": [
                         *         {
                         *           "id": "TECTONIC_UNITS",
                         *           "name": "Tectonic Units",
                         *           "filterable": true,
                         *           "availableFilters": [
                         *             {
                         *               "id": "f-chronostrat-term",
                         *               "name": "Filter by Chronostratigraphy term",
                         *               "title": "Filter by Chronostratigraphy term",
                         *               "description": "Filter by chronostratigraphic intervals"
                         *             },
                         *             {
                         *               "id": "f-tectonic-term",
                         *               "name": "Filter by Tectonic Units term",
                         *               "title": "Filter by Tectonic Units term",
                         *               "description": "Filter by tectonic units"
                         *             }
                         *           ]
                         *         },
                         *         {
                         *           "id": "GC_BEDROCK",
                         *           "name": "Bedrock Geology",
                         *           "filterable": true,
                         *           "availableFilters": [
                         *             {
                         *               "id": "f-chronostrat-term",
                         *               "name": "Filter by Chronostratigraphy term",
                         *               "title": "Filter by Chronostratigraphy term",
                         *               "description": "Filter by chronostratigraphic intervals"
                         *             },
                         *             {
                         *               "id": "f-tectonic-term",
                         *               "name": "Filter by Tectonic Units term",
                         *               "title": "Filter by Tectonic Units term",
                         *               "description": "Filter by tectonic units"
                         *             },
                         *             {
                         *               "id": "f-lithostrat-term",
                         *               "name": "Filter by Lithostratigraphy term",
                         *               "title": "Filter by Lithostratigraphy term",
                         *               "description": "Filter by lithostratigraphic units"
                         *             },
                         *             {
                         *               "id": "f-lithology-term",
                         *               "name": "Filter by Lithology term",
                         *               "title": "Filter by Lithology term",
                         *               "description": "Filter by lithology classes"
                         *             },
                         *             {
                         *               "id": "f-byAttribute",
                         *               "name": "Filter by Attribute",
                         *               "title": "Filter by Attribute",
                         *               "description": "Filter by attribute key/value"
                         *             }
                         *           ]
                         *         },
                         *         {
                         *           "id": "GC_UNCO_DEPOSITS",
                         *           "name": "Unconsolidated Deposits",
                         *           "filterable": true,
                         *           "availableFilters": [
                         *             {
                         *               "id": "f-chronostrat-term",
                         *               "name": "Filter by Chronostratigraphy term",
                         *               "title": "Filter by Chronostratigraphy term",
                         *               "description": "Filter by chronostratigraphic intervals"
                         *             }
                         *           ]
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["inline_response_200"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layers/{layerId}/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get enabled filters for a specific layer */
        get: {
            parameters: {
                query?: {
                    /** @description Language for filter labels and descriptions */
                    lang?: "en" | "it" | "de" | "fr";
                };
                header?: never;
                path: {
                    layerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Enabled filters for the specified layer */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["inline_response_200_1"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layers/{layerId}/defaultFilters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get default filters for a layer and a vocabulary term
         * @description Returns the default filters that should be applied to visualize the provided vocabulary term on the selected layer. The vocabulary is inferred from the term URI. If the layer does not support the inferred vocabulary, the endpoint returns an error.
         */
        get: {
            parameters: {
                query: {
                    /** @description Vocabulary term URI used to infer the vocabulary and build the default filter */
                    term: string;
                };
                header?: never;
                path: {
                    layerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default filters for the specified layer and term */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DefaultFiltersResponse"];
                    };
                };
                /** @description The layer does not support the vocabulary inferred from the provided term URI */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "code": 400,
                         *       "message": "Layer does not support the vocabulary inferred from the provided term"
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layers/{layerId}/attributeList": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get available attributes for filter by attribute on a specific layer */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    layerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Attribute list for the specified layer */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["inline_response_200_2"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocabularies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the list of available vocabularies */
        get: {
            parameters: {
                query?: {
                    /** @description Language for vocabulary labels */
                    lang?: "en" | "it" | "de" | "fr";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of vocabularies */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "vocabularies": [
                         *         {
                         *           "id": "chronostratigraphy",
                         *           "name": "Chronostratigraphy"
                         *         },
                         *         {
                         *           "id": "tectonic-units",
                         *           "name": "Tectonic Units"
                         *         },
                         *         {
                         *           "id": "lithostratigraphy",
                         *           "name": "Lithostratigraphy"
                         *         },
                         *         {
                         *           "id": "lithology",
                         *           "name": "Lithology"
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["VocabulariesList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocabularies/chronostratigraphy/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all Chronostratigraphy terms */
        get: {
            parameters: {
                query?: {
                    /** @description Language for vocabulary related data */
                    lang?: "en" | "it" | "de" | "fr";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of Chronostratigraphy terms */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "terms": [
                         *         {
                         *           "term": "https://lexic.swissgeol.ch/Quaternary",
                         *           "label": "Quaternary",
                         *           "description": "Mock description for the Quaternary chronostratigraphy term.",
                         *           "breadcrumbs": {
                         *             "0": "Home",
                         *             "1": "Chronostratigraphy",
                         *             "2": "Quaternary"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://lexic.swissgeol.ch/Neogene",
                         *           "label": "Neogene",
                         *           "description": "Mock description for the Neogene chronostratigraphy term.",
                         *           "breadcrumbs": {
                         *             "0": "Home",
                         *             "1": "Chronostratigraphy",
                         *             "2": "Neogene"
                         *           }
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["VocabularyTerms"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocabularies/tectonic-units/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all Tectonic Units terms */
        get: {
            parameters: {
                query?: {
                    /** @description Language for vocabulary related data */
                    lang?: "en" | "it" | "de" | "fr";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of Tectonic Units terms */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "terms": [
                         *         {
                         *           "term": "https://lexic.swissgeol.ch/Helvetic",
                         *           "label": "Helvetic",
                         *           "description": "Mock description for the Helvetic tectonic units term.",
                         *           "breadcrumbs": {
                         *             "0": "Home",
                         *             "1": "Tectonic Units",
                         *             "2": "Helvetic"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://lexic.swissgeol.ch/Penninic",
                         *           "label": "Penninic",
                         *           "description": "Mock description for the Penninic tectonic units term.",
                         *           "breadcrumbs": {
                         *             "0": "Home",
                         *             "1": "Tectonic Units",
                         *             "2": "Penninic"
                         *           }
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["VocabularyTerms"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocabularies/lithostratigraphy/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all Lithostratigraphy terms */
        get: {
            parameters: {
                query?: {
                    /** @description Language for vocabulary related data */
                    lang?: "en" | "it" | "de" | "fr";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of Lithostratigraphy terms */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "terms": [
                         *         {
                         *           "term": "https://lexic.swissgeol.ch/Molasse",
                         *           "label": "Molasse",
                         *           "description": "Mock description for the Molasse lithostratigraphy term.",
                         *           "breadcrumbs": {
                         *             "0": "Home",
                         *             "1": "Lithostratigraphy",
                         *             "2": "Molasse"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://lexic.swissgeol.ch/Servino",
                         *           "label": "Servino",
                         *           "description": "Mock description for the Servino lithostratigraphy term.",
                         *           "breadcrumbs": {
                         *             "0": "Home",
                         *             "1": "Lithostratigraphy",
                         *             "2": "Servino"
                         *           }
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["VocabularyTerms"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocabularies/lithology/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all Lithology terms */
        get: {
            parameters: {
                query?: {
                    /** @description Language for vocabulary related data */
                    lang?: "en" | "it" | "de" | "fr";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of Lithology terms */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "terms": [
                         *         {
                         *           "term": "https://lexic.swissgeol.ch/Rock",
                         *           "label": "Rock",
                         *           "description": "Mock description for the Rock lithology term.",
                         *           "breadcrumbs": {
                         *             "0": "Home",
                         *             "1": "Lithology",
                         *             "2": "Rock"
                         *           }
                         *         },
                         *         {
                         *           "term": "https://lexic.swissgeol.ch/Breccia",
                         *           "label": "Breccia",
                         *           "description": "Mock description for the Breccia lithology term.",
                         *           "breadcrumbs": {
                         *             "0": "Home",
                         *             "1": "Lithology",
                         *             "2": "Breccia"
                         *           }
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["VocabularyTerms"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocabularies/chronostratigraphy/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get layers filterable by Chronostratigraphy vocabulary */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of layers with filters on Chronostratigraphy vocabulary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "layers": [
                         *         {
                         *           "id": "tecto_units_augm",
                         *           "name": "Tectonic Units"
                         *         },
                         *         {
                         *           "id": "gc_bedrock",
                         *           "name": "GC_BEDROCK"
                         *         },
                         *         {
                         *           "id": "gc_unco_deposits",
                         *           "name": "GC_UNCO_DEPOSITS"
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["VocabularyLayersResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocabularies/tectonic-units/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get layers filterable by Tectonic Units vocabulary */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of layers with filters on Tectonic Units vocabulary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "layers": [
                         *         {
                         *           "id": "tecto_units_augm",
                         *           "name": "Tectonic Units"
                         *         },
                         *         {
                         *           "id": "gc_bedrock",
                         *           "name": "GC_BEDROCK"
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["VocabularyLayersResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocabularies/lithostratigraphy/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get layers filterable by Lithostratigraphy vocabulary */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of layers with filters on Lithostratigraphy vocabulary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "layers": [
                         *         {
                         *           "id": "gc_bedrock",
                         *           "name": "GC_BEDROCK"
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["VocabularyLayersResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocabularies/lithology/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get layers filterable by Lithology vocabulary */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of layers with filters on Lithology vocabulary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "layers": [
                         *         {
                         *           "id": "gc_bedrock",
                         *           "name": "GC_BEDROCK"
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["VocabularyLayersResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a WMS Base URL for a filtered layer (semantic query applied) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "webmapId": "SwissTopoMap",
                     *       "layerId": "GC_BEDROCK",
                     *       "filters": [
                     *         {
                     *           "filterId": "f-chronostrat-term",
                     *           "parameters": {
                     *             "type": "From-To",
                     *             "from": "Jurassic",
                     *             "to": "Cretaceous"
                     *           }
                     *         },
                     *         {
                     *           "filterId": "f-lithology-term",
                     *           "parameters": {
                     *             "term": "limestone",
                     *             "includeNarrowers": true
                     *           }
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["WmsRequest"];
                };
            };
            responses: {
                /** @description WMS endpoint with filtered layer */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "url": "https://wms.example.com/geoserver/wms?service=WMS&version=1.3.0&request=GetMap&layers=GC_BEDROCK&crs=EPSG:3857&bbox=700000,100000,800000,200000&width=256&height=256&format=image/png&transparent=true&CQL_FILTER=f-chronostrat-term( From-To , Jurassic , Cretaceous ) AND f-lithology-term( limestone , true )",
                         *       "mimeType": "image/png",
                         *       "note": "The WMS URL includes encoded semantic query parameters."
                         *     }
                         */
                        "application/json": components["schemas"]["WmsResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Layer: {
            id?: string;
            name?: string;
            filterable?: boolean;
            availableFilters?: components["schemas"]["Layer_availableFilters"][];
        };
        Filter: {
            /** @enum {string} */
            id?: "f-chronostrat-term" | "f-tectonic-term" | "f-lithostrat-term" | "f-lithology-term" | "f-byAttribute";
            name?: string;
            title?: string;
            description?: string;
        };
        ChronostratigraphyFilterParameter: {
            /** @enum {string} */
            type: "Younger" | "From-To" | "Older";
            /** @description From term (required if type is From-To or Older) */
            from?: string;
            /** @description To term (required if type is From-To or Younger) */
            to?: string;
        };
        TermFilterParameter: {
            /** @description Selected term from vocabulary */
            term: string;
            /**
             * @description Whether to include narrower terms
             * @default true
             */
            includeNarrowers: boolean;
        };
        ByAttributeFilterParameter: {
            /** @description Attribute key available from /layers/{layerId}/attributeList */
            attribute: string;
            /** @description Attribute value to match */
            value: string | number | boolean;
        };
        WmsRequest: {
            webmapId: string;
            layerId: string;
            /** @description List of applied filters and their parameter values */
            filters?: components["schemas"]["WmsRequest_filters"][];
        };
        WmsRequest_filters: {
            /** @enum {string} */
            filterId?: "f-chronostrat-term" | "f-tectonic-term" | "f-lithostrat-term" | "f-lithology-term" | "f-byAttribute";
            parameters?: components["schemas"]["ChronostratigraphyFilterParameter"] | components["schemas"]["TermFilterParameter"] | components["schemas"]["ByAttributeFilterParameter"];
        };
        WmsResponse: {
            /** @description Fully formed WMS GetMap URL for filtered layer */
            url?: string;
            /** @example image/png */
            mimeType?: string;
            /** @example WMS URL includes encoded semantic query parameters. */
            note?: string;
        };
        Error: {
            code?: number;
            message?: string;
        };
        inline_response_200: {
            webmapId?: string;
            layers?: components["schemas"]["Layer"][];
        };
        inline_response_200_1: {
            layerId?: string;
            filters?: components["schemas"]["Filter"][];
        };
        inline_response_200_2: {
            layerId?: string;
            attributes?: string[];
        };
        Layer_availableFilters: {
            id?: string;
            name?: string;
            title?: string;
            description?: string;
        };
        DefaultFiltersResponse: {
            layerId: string;
            /** @description Default filters to apply when visualizing the selected vocabulary term on the map */
            filters: components["schemas"]["WmsRequest_filters"][];
        };
        VocabulariesList: {
            vocabularies?: components["schemas"]["VocabularyDescriptor"][];
        };
        VocabularyDescriptor: {
            id?: string;
            name?: string;
        };
        VocabularyTerms: {
            terms?: components["schemas"]["VocabularyTerm"][];
        };
        VocabularyTerm: {
            /** Format: uri */
            term?: string;
            label?: string;
            description?: string;
            /** @description Ordered breadcrumb map. Keys represent numeric positions and are serialized as strings in JSON, for example "0", "1", "2". */
            breadcrumbs?: {
                [key: string]: string;
            };
        };
        VocabularyLayerRef: {
            id?: string;
            name?: string;
        };
        VocabularyLayersResponse: {
            layers?: components["schemas"]["VocabularyLayerRef"][];
        };
    };
    responses: {
        /** @description Bad Request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
